"use client";

import { SectionWrapper } from "@/components/shared/SectionWrapper";
import { AnimatedSection } from "@/components/shared/AnimatedSection";

export default function TermsPage() {
    return (
        <main className="min-h-screen pt-32 pb-20">
            <div className="container-narrow">
                <AnimatedSection>
                    <h1 className="text-display-2 font-serif text-text-primary mb-4">Terms of Service</h1>
                    <p className="text-text-muted mb-12">Last updated: March 5, 2024</p>

                    <div className="prose prose-slate max-w-none space-y-8 text-text-secondary leading-relaxed">
                        <section className="p-6 bg-oppr-primary/5 rounded-xl border border-oppr-primary/10 mb-10">
                            <h2 className="text-xl font-bold text-oppr-primary mb-3">Important Evaluation Terms</h2>
                            <p className="text-sm italic">
                                These terms govern your use of the Basic Service of Oppr B.V. If you use Oppr B.V. on behalf of another entity (such as your employer), you must have the authority to accept these Terms on their behalf.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-text-primary mb-4">1. Use of Service</h2>
                            <p>
                                We grant you a non-exclusive right to use the Oppr B.V. Services. Access data is specific to the user to whom it is issued and may not be shared, even within the same organization.
                            </p>
                            <p className="mt-4">
                                You will take reasonable steps to prevent unauthorized use of the Service and you will immediately notify us if you become aware of any material unauthorized use.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-text-primary mb-4">2. AI Output Disclaimer</h2>
                            <p>
                                Oppr B.V. is a manufacturing management tool, and its output is not legal or operational advice. The output of Oppr B.V. is generated by AI and may contain errors and inaccuracies or be incomplete. Users must always verify AI-generated suggestions against factory safety protocols.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-text-primary mb-4">3. Updates to Terms</h2>
                            <p>
                                Oppr B.V. may update the Terms by posting updated Terms on our website. All changes become effective when they are posted. Such changes are not retroactive, but your continued use of Oppr B.V. after such changes constitutes your agreement to such changes.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-text-primary mb-4">4. Force Majeure</h2>
                            <p>
                                Neither party shall be liable to the other for any delay or failure in performance under these Terms arising from any cause outside its reasonable control, including but not limited to, acts of God, labor disputes, systemic electrical or telecommunications failures, or public health emergencies.
                            </p>
                        </section>

                        <section className="pt-8 border-t border-border-light">
                            <h2 className="text-2xl font-bold text-text-primary mb-4">Contact Information</h2>
                            <p>
                                For any questions regarding these Terms, please contact us at <strong>data@hulpmetrecht.nl</strong> or via the contact forms on <strong>oppr.ai</strong>.
                            </p>
                        </section>
                    </div>
                </AnimatedSection>
            </div>
        </main>
    );
}
