/**
 * Article data layer — reads from data/articles.json (generated by seed script).
 *
 * Workflow:
 * 1. Add articles to scripts/seed.ts
 * 2. Run: npx tsx scripts/seed.ts
 * 3. This generates data/articles.json
 * 4. Next.js reads it at build time
 */

import fs from "fs";
import path from "path";
import type { Article, ArticleCategory } from "@/data/article-types";

// Re-export types and constants
export type { Article, ArticleCategory } from "@/data/article-types";
export { categoryLabels, categoryColors } from "@/data/article-types";

/* ── Load articles from JSON ── */

function loadArticles(): Article[] {
  const jsonPath = path.join(process.cwd(), "data", "articles.json");
  if (!fs.existsSync(jsonPath)) {
    return [];
  }
  const raw = fs.readFileSync(jsonPath, "utf-8");
  return JSON.parse(raw) as Article[];
}

/** All articles (including drafts) — used by generateStaticParams */
export const articles: Article[] = loadArticles();

export function getPublishedArticles(): Article[] {
  return articles
    .filter((a) => !a.draft)
    .sort(
      (a, b) =>
        new Date(b.publishedDate).getTime() -
        new Date(a.publishedDate).getTime()
    );
}

export function getFeaturedArticles(): Article[] {
  return articles
    .filter((a) => a.featured && !a.draft)
    .sort(
      (a, b) =>
        new Date(b.publishedDate).getTime() -
        new Date(a.publishedDate).getTime()
    );
}

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}

export function getRelatedArticles(
  current: Article,
  count: number = 3
): Article[] {
  const published = getPublishedArticles();
  const sameCategory = published.filter(
    (a) => a.category === current.category && a.slug !== current.slug
  );
  const others = published.filter(
    (a) => a.category !== current.category && a.slug !== current.slug
  );
  return [...sameCategory, ...others].slice(0, count);
}
